name: Build & Release Android APK

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0
  workflow_dispatch: # Manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Prebuild native Android project
      - name: Generate Android project files
        run: npx expo prebuild --platform android --no-interactive

      # 5. Set up Java JDK (required for Gradle)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 6. Set up Android SDK & tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: "33.0.2"
          ndk: "23.1.7779620"

      # 7. Provide keystore for signing
      - name: Prepare signing keys
        run: |
          mkdir -p ~/.android
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > ~/.android/upload-keystore.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      # 8. Configure Gradle signing properties
      - name: Create gradle.properties
        run: |
          cat <<EOF > android/gradle.properties
          MYAPP_UPLOAD_STORE_FILE=upload-keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      # 9. Build release APK
      - name: Build Android release APK
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon

      # 10. Archive and upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated APK release for tag ${{ github.ref_name }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
